# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.7"
#  - "2.7"

install: 
  - pip install -r requirements.txt --use-mirror

# command to run tests, e.g. python setup.py test
script:
  - py.test
